### ISSUE TITLE
Changing a profile image does not display the new image.

### ISSUE THREAD

**Issue by goupil-justin** [adamuremek/mentorship-program#199] opened 2024-04-11 23:09 UTC
Uploaded this image to a mentor profile.
![pexels-photo-4098157](https://github.com/adamuremek/mentorship-program/assets/142522764/eefea12b-e24c-4069-b341-c3d7e656288b)

This is a screen shot of the profile:
![img_1](https://github.com/adamuremek/mentorship-program/assets/142522764/3bac0073-f1af-4c89-bf15-7b707a880b71)

**Comment by goupil-justin** [comment] 2024-04-12 00:37
Verified this is still and issue.

**Comment by adamuremek** [comment] 2024-04-14 18:53
the image you have posted is of a webpixel (.webp) format. I dont know if it was intended to be, but upon uploading the image, an alert appers telling the user that you can only upload a jpg png or gif, which is correct. if you are uploading one of these file types and the issue still persists, reopen the issue, otherwise i am going to close it for now.

**Closed by adamuremek** 2024-04-14 18:53 UTC
Labels: bug
